@startuml createProject

actor "developer"

"developer" -> "client":
"client" -> "manager": create project by name
"manager" -> "manager": new project
"manager" -> "engine": init templates
"engine" -> "manager":
"manager" -> "repository": generate project structure
"repository" -> "manager":
"manager" -> "client": (error)
"client" -> "developer":

@enduml